### ISSUE TITLE
Upgrade to SpecFlow 3.0 and SimpleInjector 4.6

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [jguc/SpecFlow.SimpleInjector#4]
Hi,

do you have some plans about upgrading version of your lib to adjust to new version of specflow and simpleinjector?
If you are interested in pull requests I made some changes in branch https://github.com/AdaskoTheBeAsT/SpecFlow.SimpleInjector/tree/feature/upgrade-libs 

Branch is not finished because I am kinda lost in appveyor configuration - what should be changed there ;)

**Comment by jguc** [comment]
Hi @AdaskoTheBeAsT 
Sorry for the late response, my notifications were off as I get too many of them from other projects.
I've added the SpecFlow 3.0 and SimpleInjector 4.6 libraries and created a NuGet package 1.2 that has this support. 
If you wish to add further changes do not hesitate to create a pull request to this project.

Thanks for your contribution.
