### ISSUE TITLE
Doesn't work with specflow 2.4

### ISSUE THREAD

**Issue by ClassyCircuit** [jguc/SpecFlow.SimpleInjector#5]
Could you update this to work with specflow 2.4, please?

I have registered all types that have BindingAttribute, but whenever I start a test it fails with:

`The configuration is invalid. Creating the instance for type AllureBindings failed. The constructor of type AllureBindings contains the parameter with name 'featureContext' and type FeatureContext that is not registered. Please ensure FeatureContext is registered, or change the constructor of AllureBindings. `

This is how I registered:

```
            var types = typeof(DependencyInjection).Assembly.GetTypes()
                .Where(x => Attribute.IsDefined(x, typeof(BindingAttribute)));
            foreach (Type type in types)
            {
                Lifestyle.Singleton.CreateRegistration(type, container);
            }

            container.Register<Allure.SpecFlowPlugin.AllureBindings>();
```

**Comment by jguc** [comment]
@janissimsons project has been just updated to SpecFlow 3.0 and SimpleInjector 4.6
